# Generated by Django 5.0.4 on 2024-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='message',
            field=models.CharField(default='Example', max_length=100),
            preserve_default=False,
        ),
    ]
